### PR TITLE
compatibility with tagbar

### PR DESCRIPTION
**Pull request by tenfyzhong**

### CODE REVIEW

**Comment by Mte90** [comment]
I confirm that this works!

**Comment by weilbith** [comment]
Awesome! :tada:

**Comment by weilbith** [comment]
@xolox can't this be merged? :thinking:

**Comment by Mte90** [comment]
seems that this project is abandoned....

**Comment by Mte90** [comment]
I written an email to the author too without any answer

**Comment by Mte90** [comment]
another ping to @xolox

**Comment by Mte90** [comment]
It is time for another ping!

**Comment by weilbith** [comment]
Hmm. Maybe I just fork it. Or possibly I take it as inspiration and write my own one... :thinking:

**Comment by litchipi** [comment]
I forked the repo and applied the patch but still had some troubles with "special pages" that I want to open on startup (NERDTree and Tagbar). I got a lot of errors related to wipebuf, etc ...
So I decided to totally ignore any special page save, bypassing simply the function. Everything else works like a charm, but I personally don't care if the session doesn't include NERDTree and Tagbar.
Thought I'd share, here is the commit from my fork: [8c13ec8](https://github.com/litchipi/vim-session/commit/8baa0ccd5979b7d87f00ec041c9fc6369ba44eff)

**Pull request closed without merging**
